name: Frontend CI Pipeline

# trigger the CI on push and PRs
on:
  push:
  pull_request:

jobs:
  initialize-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: yarn install

  code-quality:
    runs-on: ubuntu-latest
    needs: initialize-pipeline
    steps:
      - name: Run lint
        run: yarn lint

      - name: Run prettier format check
        run: yarn format

  build:
    runs-on: ubuntu-latest
    needs: initialize-pipeline
    steps:
      - name: Run build
        run: yarn build
